[workspace]
members = [
    "dsa/rust",
    "http-server/rust",
    "http-server/rust-baseline",
    "http-server/rust-monoio",
    "monte-carlo-sim/rust",
    "todo-api/rust"
]
resolver = "2"

[profile.release]
panic = "abort"
lto = true
opt-level = 3
debug = "none"
codegen-units = 1
