<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <!-- <GenerateDocumentationFile>true</GenerateDocumentationFile> -->
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
    <Features>strict</Features>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeblocks>true</AllowUnsafeblocks>
  </PropertyGroup>

  <PropertyGroup>
    <DotNetVersion>8.0.0</DotNetVersion>
  </PropertyGroup>
</Project>
