<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <!-- Global/build -->
    <GlobalPackageReference Include="CSharpier.MsBuild" Version="0.28.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </GlobalPackageReference>
    <GlobalPackageReference Include="Nullable.Extended.Analyzer" Version="1.15.6169">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </GlobalPackageReference>
    <GlobalPackageReference Include="SonarAnalyzer.CSharp" Version="9.30.0.95878">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </GlobalPackageReference>
    <GlobalPackageReference Include="SvSoft.Analyzers.ClosedTypeHierarchyDiagnosticSuppression" Version="1.1.0" PrivateAssets="All" />

    <!-- Deps -->
    <PackageVersion Include="ConsoleAppFramework" Version="5.2.3" />
    <PackageVersion Include="Spectre.Console" Version="0.49.1" />
    <PackageVersion Include="System.IO.Hashing" Version="8.0.0" />

    <!-- Testing -->
    <PackageVersion Include="coverlet.collector" Version="6.0.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageVersion Include="xunit" Version="2.5.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>
</Project>
