[package]
name = "distsys"
version = "0.1.0"
edition = "2021"

[dependencies]
async-stream = "0.3.5"
serde = "1.0.188"
serde_json = "1.0.107"
tokio = { version = "1.32.0", features = ["full"] }
tokio-stream = "0.1.14"
