build:
  cargo build --release

test-echo: build
  ../../../maelstrom/maelstrom test -w echo --bin ../../target/release/distsys -- node-count 1 --time-limit 10

test-unique-ids: build
  ../../../maelstrom/maelstrom test -w unique-ids --bin ../../target/release/distsys --time-limit 30 --rate 1000 --node-count 3 --availability total --nemesis partition

test-single-broadcast: build
  ../../../maelstrom/maelstrom test -w broadcast --bin ../../target/release/distsys --node-count 1 --time-limit 20 --rate 10

test-multi-broadcast: build
  ../../../maelstrom/maelstrom test -w broadcast --bin ../../target/release/distsys --node-count 5 --time-limit 20 --rate 10

test-multi-broadcast-fault-tolerant: build
  ../../../maelstrom/maelstrom test -w broadcast --bin ../../target/release/distsys --node-count 5 --time-limit 20 --rate 10 --nemesis partition

serve:
  ../../../maelstrom/maelstrom serve

